## Series
La classe Series (sur *Pandas*) permet la manipulation des séries de valeurs indexées (bref, une séquence de valeurs de type *<key, value>*), particulièrement appréciées pour la manipulation des séries temporelles. 
 

In [4]:
from pandas import Series
maserie = Series ( [8, 70, 320, 1200], index=["Suisse", "France", "USA", "Chine"])
print(maserie)

Suisse       8
France      70
USA        320
Chine     1200
dtype: int64


On peut créer une série à partir d'une liste, d'un dictionnaire ou même d'un Array NumPy. 

In [5]:
import numpy as np

monarray = np.random.randn(5)
s2 = Series (monarray, index=["A","B","C","D","E"])

print (monarray,'\n', s2)

[-0.96850466 -1.99478449 -1.6655539  -1.22318014 -0.35159315] 
 A   -0.968505
B   -1.994784
C   -1.665554
D   -1.223180
E   -0.351593
dtype: float64


Attention par contre à la référence : l'objet Series fera toujours référence à l'objet d'origine (c'est une vue, pas une copie). Si celui-ci est modifié, la série le sera aussi. 

In [6]:
monarray[1]=-14
print(s2)

A    -0.968505
B   -14.000000
C    -1.665554
D    -1.223180
E    -0.351593
dtype: float64


On peut faire une copie d'un array avec *copy*, mais **attention** à la conso mémoire.  

In [7]:
s2 = Series (monarray.copy(), index=['A','B','C','D','E'])
print (s2)
monarray[1] = 22
print (monarray,'\n',s2)

A    -0.968505
B   -14.000000
C    -1.665554
D    -1.223180
E    -0.351593
dtype: float64
[-0.96850466 22.         -1.6655539  -1.22318014 -0.35159315] 
 A    -0.968505
B   -14.000000
C    -1.665554
D    -1.223180
E    -0.351593
dtype: float64


Concernant les listes, on a également l'opération *copy* pour faire une copie de la liste sur une nouvelle liste. L'opérateur **":"** fait également une **copie** d'une **liste**, alors que sur un **array** Numpy, il fait une **vue**. 

In [9]:
maliste = [2, 3, 5, -10, 15]
l2 = maliste.copy()
l3 = maliste[:]
l4 = maliste

maliste[1] = -4
print(maliste, l2, l3, l4)

a2 = monarray[:]
print (monarray, '\n', a2)
monarray[1] = -5.0
print (monarray,'\n', a2)


[2, -4, 5, -10, 15] [2, 3, 5, -10, 15] [2, 3, 5, -10, 15] [2, -4, 5, -10, 15]
[-0.96850466 -5.         -1.6655539  -1.22318014 -0.35159315] 
 [-0.96850466 -5.         -1.6655539  -1.22318014 -0.35159315]
[-0.96850466 -5.         -1.6655539  -1.22318014 -0.35159315] 
 [-0.96850466 -5.         -1.6655539  -1.22318014 -0.35159315]


### Récupération des valeurs ###
on peut récupérer des valeurs dans une série par leur index ou par leur valeurs. 

In [16]:
print (maserie)
# par index
horsEU = maserie[["USA","Chine"]]
print(horsEU)
print(type(horsEU))

#par valeur --> requête
petits = maserie[maserie<100]
print('Petits :', petits)

milieu = maserie[(maserie>100) & (maserie<1000)]
print('Milieu :', milieu)

# ou par position 
maserie[1:3]


Suisse       8
France      70
USA        320
Chine     1200
dtype: int64
USA       320
Chine    1200
dtype: int64
<class 'pandas.core.series.Series'>
Petits : Suisse     8
France    70
dtype: int64
Milieu : USA    320
dtype: int64


France     70
USA       320
dtype: int64